Repository biosimulations/biosimulations, pull requests merged in 2020-12, with the labels that each got.

#1587 Ci
  .github/workflows/ci2.yml
  biosimulations/apps/account-api/src/app/account.model.ts
  hooks/build
Labels: PR: unreviewed

#1520 Make Simulation-run route to run simulation
  biosimulations/angular.json
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.spec.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.module.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/resources/models/models.controller.ts
  biosimulations/apps/dispatch-service/src/app/resources/models/models.module.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.spec.ts
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/messages/.eslintrc
  biosimulations/libs/messages/messages/.eslintrc
  biosimulations/libs/messages/messages/README.md
  biosimulations/libs/messages/messages/jest.config.js
  biosimulations/libs/messages/messages/src/index.ts
  biosimulations/libs/messages/messages/src/lib/dispatch.ts
  biosimulations/libs/messages/messages/src/lib/messages.ts
  biosimulations/libs/messages/messages/tsconfig.json
  biosimulations/libs/messages/messages/tsconfig.lib.json
  biosimulations/libs/messages/messages/tsconfig.spec.json
  biosimulations/nx.json
  biosimulations/tsconfig.base.json
Labels: PR: unreviewed

#1607 Simulation Submission Bug Fixes
  .github/workflows/ci2.yml
  biosimulations/apps/dispatch-api/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.ts
  biosimulations/libs/messages/messages/src/lib/dispatch.ts
  biosimulations/libs/messages/messages/src/lib/messages.ts
Labels: PR: reviewed-approved, automerge

#1606 runBioSimulations frontend fixes and improvements
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.service.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.dto.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/resources/models/models.service.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/components/help/about/about.component.html
  biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html
  biosimulations/apps/dispatch/src/app/components/help/help/help.component.html
  biosimulations/apps/dispatch/src/app/components/home/home.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/datamodel.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation-status.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/services/visualisation/visualisation.service.ts
  biosimulations/apps/dispatch/src/assets/config.json
  biosimulations/apps/platform/src/app/help/about/about.component.html
  biosimulations/apps/platform/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/standards/overview/overview.component.html
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-interfaces.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-simulation.model.ts
  biosimulations/libs/shared/content/src/lib/policies/dispatch-privacy-policy.component.html
  biosimulations/libs/shared/content/src/lib/policies/dispatch-terms-of-service.component.html
  biosimulations/libs/shared/content/src/lib/policies/platform-privacy-policy.component.html
  biosimulations/libs/shared/content/src/lib/policies/platform-terms-of-service.component.html
  biosimulations/libs/shared/content/src/lib/policies/simulators-privacy-policy.component.html
  biosimulations/libs/shared/content/src/lib/policies/simulators-terms-of-service.component.html
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.html
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.scss
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.ts
Labels: PR: reviewed-approved

#1630 Job Submission Uses new API
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch/proxy.conf.json
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation-status.service.ts
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/dispatch/api-models/src/index.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRun.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRunStatus.ts
Labels: PR: reviewed-approved

#1633 Minor dispatch fixes
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.scss
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
Labels: PR: unreviewed

#1629 JSON conversion and archive working
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/submission.controller.ts
  biosimulations/apps/dispatch/proxy.conf.json
Labels: PR: unreviewed

#1635 Deploy
  .github/workflows/autoApproveDaemonPRs.yml
  .github/workflows/cd.yml
  .github/workflows/ci2.yml
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.service.ts
  biosimulations/apps/dispatch-api/src/main.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/resources/models/models.service.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch-service/src/app/submission.controller.ts
  biosimulations/apps/dispatch/proxy.conf.json
  biosimulations/apps/dispatch/src/app/components/help/about/about.component.html
  biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html
  biosimulations/apps/dispatch/src/app/components/help/help/help.component.html
  biosimulations/apps/dispatch/src/app/components/home/home.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.scss
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/datamodel.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation-status.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/services/visualisation/visualisation.service.ts
  biosimulations/apps/dispatch/src/assets/config.json
  biosimulations/apps/platform/src/app/help/about/about.component.html
  biosimulations/apps/platform/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/standards/overview/overview.component.html
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/dispatch/api-models/src/index.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-interfaces.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-simulation.model.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRun.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRunStatus.ts
  biosimulations/libs/shared/content/src/lib/policies/dispatch-privacy-policy.component.html
  biosimulations/libs/shared/content/src/lib/policies/dispatch-terms-of-service.component.html
  biosimulations/libs/shared/content/src/lib/policies/platform-privacy-policy.component.html
  biosimulations/libs/shared/content/src/lib/policies/platform-terms-of-service.component.html
  biosimulations/libs/shared/content/src/lib/policies/simulators-privacy-policy.component.html
  biosimulations/libs/shared/content/src/lib/policies/simulators-terms-of-service.component.html
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.html
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.scss
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.ts
Labels: PR: unreviewed

#1660 simplifying plot resizing
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.ts
Labels: PR: reviewed-approved

#1667 proofreading simulators app, updating documentation about output formats
  biosimulations/apps/platform/src/app/help/about/about.component.html
  biosimulations/apps/platform/src/app/help/faq/faq.component.html
  biosimulations/apps/platform/src/app/home/home.component.html
  biosimulations/apps/simulators/src/app/help/about/about.component.html
  biosimulations/apps/simulators/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/home/home.component.html
  biosimulations/apps/simulators/src/app/standards/overview/overview.component.html
  biosimulations/apps/simulators/src/app/standards/simulation-reports/simulation-reports.component.html
  biosimulations/apps/simulators/src/app/standards/simulation-reports/simulation-reports.component.sass
  biosimulations/apps/simulators/src/app/standards/simulator-images/simulator-images.component.html
  biosimulations/apps/simulators/src/app/standards/simulator-interfaces/simulator-interfaces.component.html
  biosimulations/apps/simulators/src/app/standards/simulator-specs/simulator-specs.component.html
  biosimulations/libs/shared/styles/src/lib/_global.scss
Labels: PR: reviewed-approved

#1637 Simulations working e2e with dispatch frontend
  biosimulations/apps/dispatch-api/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/app.module.ts
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/main.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/app.service.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch-service/src/app/submission.controller.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/services/visualisation/visualisation.service.ts
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRun.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRunStatus.ts
  biosimulations/libs/messages/messages/src/lib/dispatch.ts
Labels: PR: reviewed-approved

#1651 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1686 Refactoring and Cleanup
  biosimulations/.eslintrc
  biosimulations/apps/dispatch-api/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/app.module.ts
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.controller.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.module.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.service.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/app.service.ts
  biosimulations/apps/dispatch-service/src/app/resources/models/models.module.ts
  biosimulations/apps/dispatch-service/src/app/resources/models/models.service.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.ts
  biosimulations/apps/dispatch-service/src/app/services/auth/auth.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/auth/auth.service.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/submission.controller.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.controller.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/libs/dispatch/api-models/src/index.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-interfaces.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-simulation.model.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/index.ts
  biosimulations/libs/dispatch/api-models/src/lib/dispatch-api-models.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRunStatus.ts
  biosimulations/libs/messages/messages/src/index.ts
  biosimulations/libs/messages/messages/src/lib/dispatch.ts
  biosimulations/libs/messages/messages/src/lib/messages.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1685 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1694 updating simulator curation level for data model changes
  biosimulations/libs/shared/services/src/lib/utils/utils.service.ts
Labels: PR: unreviewed

#1700 Karr/dev dispatch fixes
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.ts
  biosimulations/apps/dispatch/src/app/datamodel.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation-status.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/assets/config.json
  biosimulations/libs/shared/services/src/lib/utils/utils.service.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.html
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.component.html
  biosimulations/libs/shared/ui/src/lib/table/table.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.interface.ts
Labels: PR: unreviewed

#1704 Karr/dev dispatch fixes 2
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.ts
  biosimulations/apps/dispatch/src/app/datamodel.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation-status.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/services/visualisation/visualisation.service.ts
  biosimulations/apps/platform/src/app/shared/models/simulation-run-status.ts
  biosimulations/apps/platform/src/app/shared/models/simulation-status.ts
  biosimulations/apps/platform/src/app/shared/models/simulation.ts
  biosimulations/libs/datamodel/common/src/lib/core/simulation-results.ts
Labels: PR: unreviewed

#1706 fixing tracking of whether simulation was submitted locally
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
Labels: PR: unreviewed

#1708 Update Sitemaps
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
Labels: PR: reviewed-approved, automerge

#1707 adding documentation for continuous integration
  biosimulations/apps/simulators/src/app/help/help/help.component.html
Labels: PR: unreviewed

#1710 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1716 Karr/dev dispatch
  biosimulations/apps/dispatch/.eslintrc
  biosimulations/apps/dispatch/src/app/components/simulations/simulations.module.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualisation/visualisation.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualization/visualization.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualization/visualization.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualization/visualization.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/visualization/visualization.component.ts
  biosimulations/apps/dispatch/src/app/services/visualization/visualization.service.spec.ts
  biosimulations/apps/dispatch/src/app/services/visualization/visualization.service.ts
Labels: PR: unreviewed

#1722 disabling plotting of non boolean/numeric data
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
Labels: PR: unreviewed

#1727 adding bionetgen, gillespy2 to available simulators
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
Labels: PR: unreviewed

#1739 implement getting reports
  biosimulations/apps/dispatch/src/app/app.module.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/services/visualization/visualization.service.ts
Labels: PR: unreviewed, automerge

#1744 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed, automerge

#1745 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed, automerge

#1756 Update Ontologies
  biosimulations/libs/ontology/sources/src/lib/edam.json
  biosimulations/libs/ontology/sources/src/lib/funderRegistry.json
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/linguist.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
  biosimulations/libs/ontology/sources/src/lib/sio.json
  biosimulations/libs/ontology/sources/src/lib/spdx.json
Labels: PR: reviewed-approved, automerge

#1761 Karr/dev dispatch
  biosimulations/apps/dispatch/src/app/app.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/tsconfig.spec.json
  biosimulations/apps/platform/src/app/app.component.html
  biosimulations/apps/simulators/src/app/app.component.html
  biosimulations/libs/shared/icons/src/lib/fa-icon/fa-icon.component.html
  biosimulations/libs/shared/icons/src/lib/fa-icon/fa-icon.component.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.html
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.html
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.ts
  biosimulations/libs/shared/ui/src/lib/notice/notice.component.html
  biosimulations/libs/shared/ui/src/lib/notice/notice.component.scss
  biosimulations/libs/shared/ui/src/lib/notice/notice.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/notice/notice.component.ts
  biosimulations/libs/shared/ui/src/lib/page/page.component.html
  biosimulations/libs/shared/ui/src/lib/page/page.component.scss
  biosimulations/libs/shared/ui/src/lib/privacy-policy-notice/privacy-policy-notice.component.ts
  biosimulations/libs/shared/ui/src/lib/shared-ui.module.ts
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.html
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.component.html
  biosimulations/libs/shared/ui/src/lib/table/table.component.scss
  biosimulations/libs/shared/ui/src/lib/table/table.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.interface.ts
Labels: PR: unreviewed

#1758 adding Dockerfile best practices from Syslabs
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/standards/simulator-images/simulator-images.component.html
Labels: PR: reviewed-approved

#1765 Save omex download logs in output instead of errors
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: PR: reviewed-approved

#1757 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1772 debugging URL fragments
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.component.ts
Labels: PR: unreviewed

#1774 Deploy fixes to BioSimulators, new SED-ML documentation, AMICI
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/simulators/src/app/app.component.html
  biosimulations/apps/simulators/src/app/standards/simulation-experiments/simulation-experiments.component.html
  biosimulations/apps/simulators/src/app/standards/simulation-experiments/simulation-experiments.component.sass
  biosimulations/apps/simulators/src/app/standards/simulation-experiments/simulation-experiments.component.spec.ts
  biosimulations/apps/simulators/src/app/standards/simulation-experiments/simulation-experiments.component.ts
  biosimulations/apps/simulators/src/app/standards/simulator-interfaces/simulator-interfaces.component.html
  biosimulations/apps/simulators/src/app/standards/standards-routing.module.ts
  biosimulations/apps/simulators/src/app/standards/standards.module.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.component.ts
Labels: PR: unreviewed

#1775 SBATCH script hotfix for DNS issues
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: PR: unreviewed

#1782 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1785 generate results archive
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
Labels: PR: unreviewed

#1784 Karr/dispatch
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/simulators/src/app/home/home.component.html
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/ui/src/lib/home/home-teaser-button.component.scss
  biosimulations/libs/shared/ui/src/lib/page/page.component.html
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.html
  biosimulations/libs/shared/ui/src/lib/table/table.component.scss
Labels: PR: unreviewed

#1787 Deploy
  .github/workflows/cancel.yml
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  LICENSE-DEPENDENCIES
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/simulators/src/app/home/home.component.html
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/ui/src/lib/home/home-teaser-button.component.scss
  biosimulations/libs/shared/ui/src/lib/page/page.component.html
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.html
  biosimulations/libs/shared/ui/src/lib/table/table.component.scss
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1788 Fixes and enhanced documentation
  biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.html
  biosimulations/apps/dispatch/src/app/components/help/help/help.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
Labels: PR: reviewed-approved

#1794 Update Ontologies
  biosimulations/libs/ontology/sources/src/lib/funderRegistry.json
  biosimulations/libs/ontology/sources/src/lib/linguist.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: reviewed-approved, automerge

#1795 Update Deployment
  biosimulations/apps/dispatch-api/src/main.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
  biosimulations/libs/ontology/sources/src/lib/funderRegistry.json
  biosimulations/libs/ontology/sources/src/lib/linguist.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: unreviewed

#1800 Adding additional example simulations
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/services/visualization/visualization.service.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/ui/src/lib/table/table.component.html
Labels: PR: unreviewed

#1803 adding documentation about SED-ML execution c895b49
  biosimulations/apps/simulators/src/app/standards/simulation-experiments/simulation-experiments.component.html
  biosimulations/apps/simulators/src/app/standards/simulator-interfaces/simulator-interfaces.component.html
  biosimulations/apps/simulators/src/app/standards/standards-routing.module.ts
Labels: PR: unreviewed

#1798 Add new VCell version 7.3.0.1p
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
Labels: PR: reviewed-approved

#1811 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1818 Karr/dev
  biosimulations/apps/simulators/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
Labels: PR: unreviewed

#1824 Update sitemap generation
  biosimulations/angular.json
  biosimulations/apps/dispatch/routes.txt
  biosimulations/apps/dispatch/src/sitemap-dynamic.xml
  biosimulations/apps/dispatch/src/sitemap-static.xml
  biosimulations/apps/dispatch/src/sitemap.xml
  biosimulations/apps/platform/routes.txt
  biosimulations/apps/platform/src/sitemap-dynamic.xml
  biosimulations/apps/platform/src/sitemap-static.xml
  biosimulations/apps/platform/src/sitemap.xml
  biosimulations/apps/simulators/routes.txt
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
  biosimulations/apps/simulators/src/sitemap-static.xml
  biosimulations/apps/simulators/src/sitemap.xml
  biosimulations/package.json
  biosimulations/tools/build-sitemaps/__main__.py
Labels: PR: unreviewed

#1817 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1830 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1835 fix url
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
Labels: PR: unreviewed

#1840 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1846 Only import languages needed for syntax highlighting
  biosimulations/apps/simulators/proxy.conf.json
  biosimulations/apps/simulators/src/app/app.module.ts
  biosimulations/apps/simulators/src/highlight.d.ts
  biosimulations/apps/simulators/tsconfig.app.json
Labels: PR: unreviewed

#1831 documenting headings for rows of reports
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/simulators/src/app/app.component.html
  biosimulations/apps/simulators/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/standards/overview/overview.component.html
  biosimulations/apps/simulators/src/app/standards/project-exec-status/project-exec-status.component.html
  biosimulations/apps/simulators/src/app/standards/project-exec-status/project-exec-status.component.sass
  biosimulations/apps/simulators/src/app/standards/project-exec-status/project-exec-status.component.spec.ts
  biosimulations/apps/simulators/src/app/standards/project-exec-status/project-exec-status.component.ts
  biosimulations/apps/simulators/src/app/standards/simulation-experiments/simulation-experiments.component.html
  biosimulations/apps/simulators/src/app/standards/simulation-reports/simulation-reports.component.html
  biosimulations/apps/simulators/src/app/standards/simulator-interfaces/simulator-interfaces.component.html
  biosimulations/apps/simulators/src/app/standards/standards-routing.module.ts
  biosimulations/apps/simulators/src/app/standards/standards.module.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
Labels: PR: unreviewed
