Repository biosimulations/biosimulations, pull requests merged in 2020-11, with the labels that each got.

#1408 Dev ontologies
  .github/workflows/updateOntologies.yml
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/package.json
  biosimulations/tools/generate-ontologies
Labels: PR: reviewed-approved

#1403 Upgrade auth
  biosimulations/apps/account-api/src/app/app.controller.ts
  biosimulations/apps/account-api/src/app/app.service.ts
  biosimulations/apps/platform-api/src/app/app.controller.spec.ts
  biosimulations/apps/platform-api/src/app/resources/models/models.controller.spec.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.spec.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.module.ts
  biosimulations/libs/auth/common/src/index.ts
  biosimulations/libs/auth/common/src/lib/authToken.ts
  biosimulations/libs/auth/common/src/lib/token.utils.ts
  biosimulations/libs/auth/nest/src/index.ts
  biosimulations/libs/auth/nest/src/lib/admin.guard.ts
  biosimulations/libs/auth/nest/src/lib/admin.strategy.ts
  biosimulations/libs/auth/nest/src/lib/admin/admin.guard.ts
  biosimulations/libs/auth/nest/src/lib/authToken.ts
  biosimulations/libs/auth/nest/src/lib/biosimulations-auth.module.ts
  biosimulations/libs/auth/nest/src/lib/jwt/jwt.guard.spec.ts
  biosimulations/libs/auth/nest/src/lib/jwt/jwt.guard.ts
  biosimulations/libs/auth/nest/src/lib/permissions/permissions.decorator.ts
  biosimulations/libs/auth/nest/src/lib/permissions/permissions.guard.ts
  biosimulations/libs/auth/nest/src/lib/strategy/jwt.strategy.ts
  biosimulations/libs/auth/nest/src/lib/strategy/secret.strategy.ts
  biosimulations/libs/auth/nest/src/lib/strategy/strategy.config.ts
  biosimulations/libs/auth/nest/src/test/authTest.controller.ts
  biosimulations/libs/auth/nest/src/test/authTest.module.ts
  biosimulations/libs/shared/exceptions/src/lib/default.filter.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
Labels: PR: unreviewed

#1420 adding method to remove simulator/version
  biosimulations/apps/simulators-api/src/app/app.module.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.service.ts
Labels: PR: unreviewed

#1424 fix schema for array objects
  biosimulations/libs/shared/exceptions/src/lib/exception.id.ts
  biosimulations/libs/shared/exceptions/src/lib/filters/Mongo/mongose-exception.filter.ts
  biosimulations/libs/shared/exceptions/src/lib/filters/Mongo/strict-mode-exception.filter.ts
  biosimulations/libs/shared/exceptions/src/lib/filters/Mongo/strict-mode-exception.ts
  biosimulations/libs/shared/exceptions/src/lib/filters/Mongo/validation-exception.filter.ts
  biosimulations/libs/shared/exceptions/src/lib/filters/mongo
  biosimulations/libs/shared/exceptions/src/lib/shared-exceptions.module.ts
  biosimulations/libs/shared/exceptions/src/lib/utils.ts
  biosimulations/libs/simulators/database-models/src/lib/common.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1431 Dev simulators
  biosimulations/angular.json
  biosimulations/apps/dispatch/src/app/components/home/home.component.html
  biosimulations/apps/dispatch/src/app/components/home/home.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/home/home.component.ts
  biosimulations/apps/dispatch/src/assets/config.json
  biosimulations/apps/platform/src/app/home/home.component.html
  biosimulations/apps/platform/src/app/home/home.component.spec.ts
  biosimulations/apps/platform/src/app/home/home.component.ts
  biosimulations/apps/platform/src/app/models/browse-models/browse-models.component.scss
  biosimulations/apps/platform/src/assets/config.json
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/home/home.component.html
  biosimulations/apps/simulators/src/app/home/home.component.spec.ts
  biosimulations/apps/simulators/src/app/home/home.component.ts
  biosimulations/apps/simulators/src/app/simulators/simulators.module.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.scss
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.spec.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/assets/config.json
  biosimulations/libs/shared/assets/src/assets/images/biosimulations-logo/logo.svg
  biosimulations/libs/shared/assets/src/assets/images/biosimulators-logo/logo-white.svg
  biosimulations/libs/shared/assets/src/assets/images/biosimulators-logo/logo.svg
  biosimulations/libs/shared/assets/src/assets/images/runbiosimulations-logo/logo.svg
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/styles/src/lib/biosimulations/biosimulations-colors.scss
  biosimulations/libs/shared/styles/src/lib/biosimulators/biosimulations-colors.scss
  biosimulations/libs/shared/ui/src/lib/bread-crumbs/bread-crumbs-button/bread-crumbs-button.component.scss
  biosimulations/libs/shared/ui/src/lib/home/home-teaser-button.component.html
  biosimulations/libs/shared/ui/src/lib/home/home-teaser-button.component.scss
  biosimulations/libs/shared/ui/src/lib/home/home-teaser-button.component.ts
  biosimulations/libs/shared/ui/src/lib/home/home-teaser.component.html
  biosimulations/libs/shared/ui/src/lib/home/home-teaser.component.scss
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.scss
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-content-section.component.scss
  biosimulations/libs/shared/ui/src/lib/topbar/topbar-menu-item.component.scss
Labels: PR: unreviewed

#1437 Delete mongo to avoid case sensitivity
  biosimulations/libs/shared/exceptions/src/lib/filters/mongo
Labels: PR: reviewed-approved

#1440 Authentication fix
  biosimulations/libs/auth/nest/src/lib/admin/admin.guard.ts
  biosimulations/libs/auth/nest/src/lib/permissions/permissions.guard.ts
Labels: PR: unreviewed

#1407 Changes by create-pull-request action
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
Labels: PR: unreviewed

#1442 Add label to dockerfile for ghcr metadata
  Dockerfile
Labels: PR: unreviewed

#1434 Changes by create-pull-request action
  biosimulations/libs/ontology/sources/src/lib/edam.json
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: unreviewed

#1383 Changes by create-pull-request action
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed

#1443 differentiating style of internal from external links
  biosimulations/apps/dispatch/src/app/components/help/help/help.component.html
  biosimulations/apps/dispatch/src/app/components/home/home.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/platform/src/app/home/home.component.html
  biosimulations/apps/simulators/src/app/help/about/about.component.html
  biosimulations/apps/simulators/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/home/home.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/libs/shared/content/src/lib/policies/dispatch-terms-of-service.component.html
  biosimulations/libs/shared/content/src/lib/policies/platform-terms-of-service.component.html
  biosimulations/libs/shared/content/src/lib/policies/simulators-terms-of-service.component.html
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/ui/src/lib/privacy-policy-notice/privacy-policy-notice.component.html
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.html
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-content-section.component.ts
Labels: PR: unreviewed

#1357 Update job status with `sacct` instead `squeue`
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.controller.ts
  biosimulations/apps/dispatch-service/src/app/app.controller.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
  biosimulations/apps/dispatch-service/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch-service/src/app/services/ssh/ssh.service.ts
  biosimulations/apps/dispatch/src/app/app.module.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-simulation.model.ts
Labels: PR: unreviewed

#1465 Update
  biosimulations/.eslintrc
  biosimulations/angular.json
  biosimulations/apps/account-api/jest.config.js
  biosimulations/apps/account/jest.config.js
  biosimulations/apps/account/src/app/components/agreement/agreement.component.ts
  biosimulations/apps/account/src/app/registration/registration.service.ts
  biosimulations/apps/dispatch-api/jest.config.js
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/resources/models/models.controller.ts
  biosimulations/apps/dispatch-service/jest.config.js
  biosimulations/apps/dispatch-service/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch/jest.config.js
  biosimulations/apps/mail-service/jest.config.js
  biosimulations/apps/ontology-api/jest.config.js
  biosimulations/apps/platform-api/jest.config.js
  biosimulations/apps/platform/jest.config.js
  biosimulations/apps/platform/src/app/home/stats.service.ts
  biosimulations/apps/platform/src/app/models/browse-models/models-datasource.ts
  biosimulations/apps/simulators-api/jest.config.js
  biosimulations/apps/simulators/jest.config.js
  biosimulations/jest.config.js
  biosimulations/jest.preset.js
  biosimulations/libs/auth/angular/jest.config.js
  biosimulations/libs/auth/angular/src/lib/auth.service.ts
  biosimulations/libs/auth/common/jest.config.js
  biosimulations/libs/auth/nest/jest.config.js
  biosimulations/libs/config/angular/jest.config.js
  biosimulations/libs/config/common/jest.config.js
  biosimulations/libs/config/nest/jest.config.js
  biosimulations/libs/config/nest/src/lib/biosimulations-auth-config.ts
  biosimulations/libs/datamodel/api/jest.config.js
  biosimulations/libs/datamodel/common/jest.config.js
  biosimulations/libs/datamodel/common/src/lib/common/license.ts
  biosimulations/libs/datamodel/database/jest.config.js
  biosimulations/libs/dispatch/api-models/jest.config.js
  biosimulations/libs/dispatch/file-modifiers/jest.config.js
  biosimulations/libs/dispatch/file-modifiers/src/lib/dispatch-file-modifiers.ts
  biosimulations/libs/messages/jest.config.js
  biosimulations/libs/ontology/ontologies/jest.config.js
  biosimulations/libs/ontology/sources/jest.config.js
  biosimulations/libs/platform/api-models/jest.config.js
  biosimulations/libs/platform/database-models/jest.config.js
  biosimulations/libs/platform/view/jest.config.js
  biosimulations/libs/shared/content/jest.config.js
  biosimulations/libs/shared/debug/jest.config.js
  biosimulations/libs/shared/environments/jest.config.js
  biosimulations/libs/shared/exceptions/jest.config.js
  biosimulations/libs/shared/icons/jest.config.js
  biosimulations/libs/shared/services/jest.config.js
  biosimulations/libs/shared/ui/jest.config.js
  biosimulations/libs/shared/ui/src/lib/table/table.component.ts
  biosimulations/libs/shared/utils/routes/jest.config.js
  biosimulations/libs/simulators/api-models/jest.config.js
  biosimulations/libs/simulators/database-models/jest.config.js
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1461 Changes by create-pull-request action
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: unreviewed

#1460 Changes by create-pull-request action
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
Labels: PR: unreviewed

#1466 Changes by create-pull-request action
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed

#1467 Ontology validation
  biosimulations/.eslintrc
  biosimulations/apps/ontology-api/src/app/app.module.ts
  biosimulations/apps/ontology-api/src/app/edam.controller.ts
  biosimulations/apps/ontology-api/src/app/kisao.controller.ts
  biosimulations/apps/ontology-api/src/app/ontologies.controller.ts
  biosimulations/apps/ontology-api/src/app/sbo.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.service.ts
  biosimulations/apps/simulators-api/tsconfig.app.json
  biosimulations/apps/simulators-api/tsconfig.spec.json
  biosimulations/libs/datamodel/api/src/lib/common/index.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontology.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontologyId.dto.ts
  biosimulations/libs/ontology/ontologies/src/index.ts
  biosimulations/libs/ontology/ontologies/src/lib/edam.controller.ts
  biosimulations/libs/ontology/ontologies/src/lib/kisao.controller.ts
  biosimulations/libs/ontology/ontologies/src/lib/ontologies.controller.spec.ts
  biosimulations/libs/ontology/ontologies/src/lib/ontologies.controller.ts
  biosimulations/libs/ontology/ontologies/src/lib/ontologies.module.ts
  biosimulations/libs/ontology/ontologies/src/lib/ontologies.service.ts
  biosimulations/libs/ontology/ontologies/src/lib/sbo.controller.ts
  biosimulations/libs/ontology/ontologies/tsconfig.spec.json
  biosimulations/libs/ontology/sources/src/lib/edam.json
  biosimulations/libs/ontology/sources/tsconfig.spec.json
  biosimulations/libs/simulators/api-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/nx.json
  biosimulations/tools/generate-ontologies
Labels: PR: unreviewed

#1489 Karr/dev simulators without images
  biosimulations/apps/simulators/.eslintrc
  biosimulations/apps/simulators/proxy.conf.json
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/simulator-table.service.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/tableSimulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/simulator.service.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.html
  biosimulations/libs/shared/ui/src/lib/table/table.component.html
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1497 Fetch supported simulators and their versions
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
Labels: PR: unreviewed

#1499 require the format field
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1484 Dispatch
  Dockerfile
  biosimulations/apps/dispatch-api/src/app/app.module.ts
  biosimulations/apps/dispatch-api/src/main.ts
  biosimulations/apps/dispatch-api/src/results/results.controller.spec.ts
  biosimulations/apps/dispatch-api/src/results/results.controller.ts
  biosimulations/apps/dispatch-api/src/results/results.dto.ts
  biosimulations/apps/dispatch-api/src/results/results.model.ts
  biosimulations/apps/dispatch-api/src/results/results.module.ts
  biosimulations/apps/dispatch-api/src/results/results.service.spec.ts
  biosimulations/apps/dispatch-api/src/results/results.service.ts
  biosimulations/apps/dispatch-api/src/simulation-run/file.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.spec.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.dto.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.module.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.spec.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1505 Changes by create-pull-request action
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed

#1506 Changes by create-pull-request action
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
Labels: PR: unreviewed

#1507 Changes by create-pull-request action
  biosimulations/libs/ontology/sources/src/lib/edam.json
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: unreviewed

#1518 Changes by create-pull-request action
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved

#1522 change env setting for ci
  .github/workflows/ci2.yml
Labels: PR: unreviewed

#1523 Ci fix
  .github/workflows/ci2.yml
Labels: PR: unreviewed

#1519 angular update migration
  biosimulations/apps/account/src/app/app.module.ts
  biosimulations/apps/dispatch/src/app/app.module.ts
  biosimulations/apps/platform/src/app/app.module.ts
  biosimulations/apps/simulators/src/app/app.module.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page-tab.component.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1548 Karr/dev ontos 2
  biosimulations/apps/account-api/src/main.ts
  biosimulations/apps/dispatch-api/src/main.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.dto.ts
  biosimulations/apps/ontology-api/src/app/app.module.ts
  biosimulations/apps/ontology-api/src/app/edam.controller.ts
  biosimulations/apps/ontology-api/src/app/kisao.controller.ts
  biosimulations/apps/ontology-api/src/app/ontologies.controller.ts
  biosimulations/apps/ontology-api/src/app/sbo.controller.ts
  biosimulations/apps/ontology-api/src/app/sio.controller.ts
  biosimulations/apps/ontology-api/src/app/spdx.controller.ts
  biosimulations/apps/ontology-api/src/main.ts
  biosimulations/apps/platform-api/src/app/resources/models/biomodel.model.ts
  biosimulations/apps/platform-api/src/main.ts
  biosimulations/apps/platform/src/app/shared/views/framework.ts
  biosimulations/apps/simulators/src/app/simulators/ontology.service.ts
  biosimulations/libs/datamodel/api/src/lib/common/license.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontology.dto.ts
  biosimulations/libs/datamodel/common/src/lib/common/ontology.ts
  biosimulations/libs/ontology/ontologies/src/lib/ontologies.service.ts
  biosimulations/libs/ontology/sources/src/lib/edamTerms.ts
  biosimulations/libs/ontology/sources/src/lib/kisaoTerms.ts
  biosimulations/libs/ontology/sources/src/lib/sboTerms.ts
  biosimulations/libs/ontology/sources/src/lib/sioTerms.ts
  biosimulations/libs/ontology/sources/src/lib/spdxTerms.ts
  biosimulations/libs/platform/api-models/src/lib/common/format.ts
  biosimulations/libs/platform/api-models/src/lib/common/license.dto.ts
  biosimulations/libs/platform/api-models/src/lib/common/ontology.dto.ts
  biosimulations/libs/simulators/api-models/src/lib/image.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/image.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1549 Update Sitemaps
  biosimulations/apps/simulators/src/sitemap-dynamic.xml
Labels: PR: reviewed-approved

#1524 Update Dependecy Licenses
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed

#1563 minor fixes to simulators app
  biosimulations/apps/platform/src/app/help/about/about.component.html
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/simulator-table.service.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/tableSimulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.scss
  biosimulations/libs/shared/ui/src/lib/table/table.component.html
  biosimulations/libs/shared/ui/src/lib/table/table.interface.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1564 Karr/dev simulators
  biosimulations/apps/account-api/src/app/account.model.ts
  biosimulations/apps/account-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.dto.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/simulator-table.service.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/tableSimulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/simulator.service.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/app/standards/simulator-specs/example-specs.json
  biosimulations/libs/datamodel/api/src/lib/common/citation.ts
  biosimulations/libs/datamodel/api/src/lib/common/format.ts
  biosimulations/libs/datamodel/api/src/lib/common/license.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontology.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontologyId.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/person.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/taxon.ts
  biosimulations/libs/datamodel/api/src/lib/common/url.ts
  biosimulations/libs/datamodel/api/src/lib/json/error.ts
  biosimulations/libs/datamodel/common/src/lib/common/image.ts
  biosimulations/libs/datamodel/common/src/lib/common/ontology.ts
  biosimulations/libs/datamodel/common/src/lib/common/url.ts
  biosimulations/libs/datamodel/common/src/lib/utils.ts
  biosimulations/libs/dispatch/api-models/src/lib/common/dispatch-simulation.model.ts
  biosimulations/libs/platform/api-models/src/lib/common/citation.ts
  biosimulations/libs/platform/api-models/src/lib/common/format.ts
  biosimulations/libs/platform/api-models/src/lib/common/license.dto.ts
  biosimulations/libs/platform/api-models/src/lib/common/ontology.dto.ts
  biosimulations/libs/platform/api-models/src/lib/common/taxon.ts
  biosimulations/libs/platform/api-models/src/lib/core/biomodels.dto.ts
  biosimulations/libs/platform/api-models/src/lib/core/identifiers.dto.ts
  biosimulations/libs/platform/api-models/src/lib/core/metadata.dto.ts
  biosimulations/libs/platform/api-models/src/lib/core/models/documents.ts
  biosimulations/libs/platform/api-models/src/lib/core/relationships.dto.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/api-models/src/lib/biosimulatorsMeta.ts
  biosimulations/libs/simulators/api-models/src/lib/image.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/common.ts
  biosimulations/libs/simulators/database-models/src/lib/image.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1565 Karr/dev simulators
  biosimulations/apps/simulators/src/app/help/about/about.component.html
  biosimulations/apps/simulators/src/app/help/faq/faq.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/home/home.component.html
  biosimulations/libs/shared/assets/src/assets/images/about/partners/kisao.svg
  biosimulations/libs/shared/assets/src/assets/images/about/partners/sbo.png
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1562 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed, automerge

#1566 Karr/dev simulators
  biosimulations/apps/platform-api/src/app/resources/models/biomodel.model.ts
  biosimulations/apps/platform/src/app/shared/models/algorithm-parameter.ts
  biosimulations/apps/platform/src/app/shared/models/model-parameter.ts
  biosimulations/apps/platform/src/app/shared/models/model-variable.ts
  biosimulations/apps/platform/src/app/shared/views/biomodelParameter.ts
  biosimulations/apps/platform/src/app/shared/views/biomodelVariable.ts
  biosimulations/apps/simulators/.eslintrc
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.scss
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/app/standards/simulator-specs/example-specs.json
  biosimulations/libs/datamodel/api/src/lib/common/ontologyId.dto.ts
  biosimulations/libs/datamodel/common/src/lib/common/index.ts
  biosimulations/libs/datamodel/common/src/lib/common/ontology.ts
  biosimulations/libs/datamodel/common/src/lib/common/value-type.ts
  biosimulations/libs/datamodel/common/src/lib/core/algorithm.ts
  biosimulations/libs/datamodel/common/src/lib/core/biomodel.ts
  biosimulations/libs/platform/api-models/src/lib/core/biomodels.dto.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
Labels: PR: unreviewed

#1570 Karr/dev simulators
  .github/workflows/updateOntologies.yml
  biosimulations/apps/ontology-api/src/app/ontologies.controller.ts
  biosimulations/apps/platform/src/app/models/browse-models/models-datasource.ts
  biosimulations/apps/platform/src/app/shared/models/ontology-term.ts
  biosimulations/apps/platform/src/app/shared/models/simulation.ts
  biosimulations/apps/platform/src/app/shared/views/framework.ts
  biosimulations/apps/simulators/.eslintrc
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/simulator-table.service.ts
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/tableSimulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/ontology.service.ts
  biosimulations/apps/simulators/src/app/simulators/simulator.service.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/app/standards/simulator-specs/example-specs.json
  biosimulations/libs/datamodel/api/src/lib/common/dependentPackage.ts
  biosimulations/libs/datamodel/api/src/lib/common/funding.ts
  biosimulations/libs/datamodel/api/src/lib/common/index.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontology.dto.ts
  biosimulations/libs/datamodel/api/src/lib/common/ontologyId.dto.ts
  biosimulations/libs/datamodel/common/src/lib/common/funding.ts
  biosimulations/libs/datamodel/common/src/lib/common/image.ts
  biosimulations/libs/datamodel/common/src/lib/common/index.ts
  biosimulations/libs/datamodel/common/src/lib/common/ontology.ts
  biosimulations/libs/datamodel/common/src/lib/common/operating-system-type.ts
  biosimulations/libs/datamodel/common/src/lib/common/url.ts
  biosimulations/libs/datamodel/common/src/lib/core/algorithm.ts
  biosimulations/libs/datamodel/common/src/lib/core/dependent-package.ts
  biosimulations/libs/datamodel/common/src/lib/core/index.ts
  biosimulations/libs/ontology/ontologies/src/lib/ontologies.service.ts
  biosimulations/libs/ontology/sources/src/index.ts
  biosimulations/libs/ontology/sources/src/lib/funderRegistry.json
  biosimulations/libs/ontology/sources/src/lib/funderRegistryTerms.ts
  biosimulations/libs/ontology/sources/src/lib/linguist.json
  biosimulations/libs/ontology/sources/src/lib/linguistTerms.ts
  biosimulations/libs/platform/api-models/src/lib/common/ontology.dto.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/api-models/src/lib/image.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/dependentPackage.ts
  biosimulations/libs/simulators/database-models/src/lib/funding.ts
  biosimulations/libs/simulators/database-models/src/lib/gitHubLanguageTerms.ts
  biosimulations/libs/simulators/database-models/src/lib/image.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/simulators-database-models.ts
  biosimulations/tools/generate-ontologies
  biosimulations/tools/generate-ontologies-requirements.txt
Labels: PR: unreviewed
