Repository biosimulations/biosimulations, pull requests merged in 2020-10, with the labels that each got.

#1291 create and use custom preloading
  biosimulations/apps/simulators/src/app/MarkedPreloadingStrategy.ts
  biosimulations/apps/simulators/src/app/app.module.ts
Labels: PR: unreviewed

#1298 Fixing URL for example COMBINE/OMEX arvhive
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
Labels: PR: reviewed-approved

#1296 Service workers
  biosimulations/angular.json
  biosimulations/apps/dispatch/ngsw-config.json
  biosimulations/apps/dispatch/src/manifest.webmanifest
Labels: PR: unreviewed

#1322 Dev error handling
  biosimulations/apps/dispatch/src/app/app.module.ts
  biosimulations/apps/platform/src/app/app.module.ts
  biosimulations/apps/platform/src/app/models/browse-models/browse-models.component.html
  biosimulations/apps/simulators/src/app/app.module.ts
  biosimulations/apps/simulators/src/app/simulators/simulators.module.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/ui/src/index.ts
  biosimulations/libs/shared/ui/src/lib/error/biosimulations-error.ts
  biosimulations/libs/shared/ui/src/lib/error/error-404.component.html
  biosimulations/libs/shared/ui/src/lib/error/error-404.component.scss
  biosimulations/libs/shared/ui/src/lib/error/error-404.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/error/error-404.component.ts
  biosimulations/libs/shared/ui/src/lib/error/error-500.component.html
  biosimulations/libs/shared/ui/src/lib/error/error-500.component.scss
  biosimulations/libs/shared/ui/src/lib/error/error-500.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/error/error-500.component.ts
  biosimulations/libs/shared/ui/src/lib/error/error-handler.ts
  biosimulations/libs/shared/ui/src/lib/error/error.component.html
  biosimulations/libs/shared/ui/src/lib/error/error.component.scss
  biosimulations/libs/shared/ui/src/lib/error/error.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/error/error.component.ts
  biosimulations/libs/shared/ui/src/lib/error/error.module.ts
  biosimulations/libs/shared/ui/src/lib/error/under-construction.component.html
  biosimulations/libs/shared/ui/src/lib/error/under-construction.component.scss
  biosimulations/libs/shared/ui/src/lib/error/under-construction.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/error/under-construction.component.ts
  biosimulations/libs/shared/ui/src/lib/error/under-maintainence.component.html
  biosimulations/libs/shared/ui/src/lib/error/under-maintainence.component.scss
  biosimulations/libs/shared/ui/src/lib/error/under-maintainence.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/error/under-maintainence.component.ts
  biosimulations/libs/shared/ui/src/lib/shared-ui.module.ts
Labels: PR: unreviewed

#1295 Create Dependabot config file
  .github/dependabot.yml
Labels: PR: unreviewed

#1328 Changes by create-pull-request action
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed

#1346 Simulator API updates
  biosimulations/angular.json
  biosimulations/apps/simulators-api/src/app/app.module.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.module.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.service.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/libs/auth/nest/src/lib/admin.strategy.ts
  biosimulations/libs/auth/nest/src/lib/jwt.strategy.ts
  biosimulations/libs/auth/nest/src/lib/permissions.guard.ts
  biosimulations/libs/shared/datamodel-api/src/lib/json/error.ts
  biosimulations/libs/shared/datamodel-api/src/lib/json/index.ts
  biosimulations/libs/shared/datamodel-api/src/lib/json/meta.ts
  biosimulations/libs/shared/datamodel-api/src/lib/shared-datamodel-api.ts
  biosimulations/libs/shared/datamodel/src/lib/common/ontology.ts
  biosimulations/libs/shared/datamodel/src/lib/core/algorithm.ts
  biosimulations/libs/shared/exceptions/.eslintrc
  biosimulations/libs/shared/exceptions/README.md
  biosimulations/libs/shared/exceptions/index.ts
  biosimulations/libs/shared/exceptions/jest.config.js
  biosimulations/libs/shared/exceptions/src/index.ts
  biosimulations/libs/shared/exceptions/src/lib/biosimulations-exception.filter.ts
  biosimulations/libs/shared/exceptions/src/lib/exception.ts
  biosimulations/libs/shared/exceptions/src/lib/shared-exceptions.module.ts
  biosimulations/libs/shared/exceptions/tsconfig.json
  biosimulations/libs/shared/exceptions/tsconfig.lib.json
  biosimulations/libs/shared/exceptions/tsconfig.spec.json
  biosimulations/libs/simulators/api-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/api-models/src/lib/ontologyId.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/.eslintrc
  biosimulations/libs/simulators/database-models/README.md
  biosimulations/libs/simulators/database-models/jest.config.js
  biosimulations/libs/simulators/database-models/src/index.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/simulators-database-models.ts
  biosimulations/libs/simulators/database-models/tsconfig.json
  biosimulations/libs/simulators/database-models/tsconfig.lib.json
  biosimulations/libs/simulators/database-models/tsconfig.spec.json
  biosimulations/nx.json
  biosimulations/tsconfig.base.json
Labels: PR: unreviewed, simulators

#1350 fixing toc
  biosimulations/apps/dispatch/src/app/components/help/about/about.component.ts
  biosimulations/apps/dispatch/src/app/components/help/faq/faq.component.ts
  biosimulations/apps/dispatch/src/app/components/help/help/help.component.ts
  biosimulations/apps/platform/src/app/help/about/about.component.ts
  biosimulations/apps/platform/src/app/help/faq/faq.component.ts
  biosimulations/apps/platform/src/app/help/help/help.component.ts
  biosimulations/apps/simulators/src/app/help/about/about.component.ts
  biosimulations/apps/simulators/src/app/help/faq/faq.component.ts
  biosimulations/apps/simulators/src/app/help/help/help.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/libs/shared/content/src/lib/policies/dispatch-privacy-policy.component.ts
  biosimulations/libs/shared/content/src/lib/policies/dispatch-terms-of-service.component.ts
  biosimulations/libs/shared/content/src/lib/policies/platform-privacy-policy.component.ts
  biosimulations/libs/shared/content/src/lib/policies/platform-terms-of-service.component.ts
  biosimulations/libs/shared/content/src/lib/policies/simulators-privacy-policy.component.ts
  biosimulations/libs/shared/content/src/lib/policies/simulators-terms-of-service.component.ts
  biosimulations/libs/shared/services/src/index.ts
  biosimulations/libs/shared/services/src/lib/utils/utils.service.spec.ts
  biosimulations/libs/shared/services/src/lib/utils/utils.service.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.ts
  biosimulations/libs/shared/ui/src/lib/table/table.component.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.html
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.ts
  biosimulations/libs/shared/ui/src/lib/toc/toc-section.directive.ts
  biosimulations/libs/shared/ui/src/lib/toc/toc-section.ts
  biosimulations/libs/shared/ui/src/lib/toc/toc-sections-container.directive.ts
Labels: PR: unreviewed

#1349 Changes by create-pull-request action
  LICENSE-DEPENDENCIES
Labels: PR: unreviewed

#1381 Dev sitemap
  .github/workflows/buildSitemaps.yml
  .github/workflows/dependencyLicense.yml
  biosimulations/tools/build-sitemaps/__main__.py
Labels: PR: unreviewed

#1380 Add BiosimulationsMeta object to schema
  biosimulations/libs/simulators/api-models/src/lib/biosimulatorsMeta.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithmParameter.ts
  biosimulations/libs/simulators/database-models/src/lib/biosimulatorsMeta.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1390 adding descriptions of API methods
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
Labels: PR: unreviewed

#1392 Bilalshaikh42/issue1310
  biosimulations/apps/platform/src/app/models/model.ts
  biosimulations/apps/platform/src/app/shared/models/algorithm.ts
  biosimulations/apps/platform/src/app/shared/models/chart-type.ts
  biosimulations/apps/platform/src/app/shared/models/journal-reference.ts
  biosimulations/apps/platform/src/app/shared/models/project-product.ts
  biosimulations/apps/platform/src/app/shared/models/project.ts
  biosimulations/apps/platform/src/app/shared/models/simulation.ts
  biosimulations/apps/platform/src/app/shared/models/top-level-resource.ts
  biosimulations/apps/platform/src/app/shared/models/visualization.ts
  biosimulations/apps/platform/src/app/shared/views/journal-reference.ts
  biosimulations/libs/platform/api-models/src/lib/common/citation.ts
  biosimulations/libs/platform/api-models/src/lib/common/externalreferences.dto.ts
  biosimulations/libs/platform/api-models/src/lib/common/index.ts
  biosimulations/libs/shared/datamodel-api/src/lib/common/citation.ts
  biosimulations/libs/shared/datamodel-api/src/lib/common/externalreferences.dto.ts
  biosimulations/libs/shared/datamodel-api/src/lib/common/index.ts
  biosimulations/libs/shared/datamodel-api/src/lib/common/ontology.dto.ts
  biosimulations/libs/shared/datamodel/src/lib/common/citation.ts
  biosimulations/libs/shared/datamodel/src/lib/common/index.ts
  biosimulations/libs/shared/datamodel/src/lib/common/ontology.ts
  biosimulations/libs/shared/datamodel/src/lib/core/algorithm.ts
  biosimulations/libs/shared/datamodel/src/lib/core/project.ts
  biosimulations/libs/shared/datamodel/src/lib/resources/resource.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/common.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1399 Dev simulators
  biosimulations/apps/platform/src/app/shared/models/simulator.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/libs/shared/datamodel/src/lib/core/simulator.ts
Labels: PR: unreviewed

#1406 Fix scrolling of non-container components
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.spec.ts
  biosimulations/libs/shared/services/src/lib/scroll/scroll.service.ts
  biosimulations/libs/shared/ui/src/lib/table/stacked-table.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.ts
Labels: PR: unreviewed

#1404 adding syntax highlighting
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/simulators/src/app/help/help.module.ts
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/help/help/help.component.spec.ts
  biosimulations/libs/shared/debug/src/lib/viewer/viewer.component.html
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed
