Repository biosimulations/biosimulations, pull requests merged in 2021-01, with the labels that each got.

#1860 Revert "Bump @nrwl/cli from 10.4.1 to 11.0.20 in /biosimulations"
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1861 Karr/dev simulators
  biosimulations/apps/simulators/.eslintrc
  biosimulations/apps/simulators/src/app/simulators/ontology.service.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/libs/datamodel/common/src/lib/core/algorithm.ts
  biosimulations/libs/datamodel/common/src/lib/core/simulator.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.html
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.spec.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.ts
  biosimulations/libs/simulators/api-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/api-models/src/lib/biosimulatorsMeta.ts
  biosimulations/libs/simulators/database-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/biosimulatorsMeta.ts
Labels: PR: unreviewed

#1865 Update Ontologies
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: reviewed-approved, automerge

#1859 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1876 use mail templates
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/mail-service/src/app/app.controller.ts
  biosimulations/libs/config/nest/src/lib/biosimulations-email.config.ts
  biosimulations/libs/mail-service/client/src/lib/mail-service-client.service.ts
Labels: PR: unreviewed

#1884 Ssh error handling
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/ssh/ssh.service.ts
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.service.ts
  biosimulations/libs/config/nest/src/lib/biosimulations-hpc-config.ts
Labels: PR: unreviewed

#1885 Updating
  biosimulations/.eslintrc.json
  biosimulations/angular.json
  biosimulations/apps/dispatch-api/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/apps/dispatch-api/src/results/results.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.spec.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch/.eslintrc
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/environments/environment.dev.ts
  biosimulations/apps/dispatch/src/environments/environment.prod.ts
  biosimulations/apps/dispatch/src/environments/environment.ts
  biosimulations/apps/platform/.eslintrc
  biosimulations/apps/platform/src/app/models/browse-models/browse-models-datasource.ts
  biosimulations/apps/platform/src/app/models/services/mockModels.ts
  biosimulations/apps/platform/src/app/shared/views/index.ts
  biosimulations/apps/platform/src/environments/environment.prod.ts
  biosimulations/apps/platform/src/environments/environment.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.service.ts
  biosimulations/apps/simulators/.eslintrc
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/environments/environment.prod.ts
  biosimulations/apps/simulators/src/environments/environment.ts
  biosimulations/libs/shared/assets/.eslintrc
  biosimulations/libs/shared/styles/.eslintrc
  biosimulations/libs/simulators/api-models/src/lib/biosimulatorsMeta.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/package-lock.json
  biosimulations/package.json
  report.20210105.220752.3102654.0.001.json
Labels: PR: unreviewed

#1877 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1905 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1907 Update deployment
  LICENSE-DEPENDENCIES
  biosimulations/.eslintrc.json
  biosimulations/angular.json
  biosimulations/apps/dispatch-api/src/app/app.controller.spec.ts
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/apps/dispatch-api/src/results/results.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.spec.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/services/hpc/hpc.service.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
  biosimulations/apps/dispatch-service/src/app/services/ssh/ssh.service.ts
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.controller.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.service.ts
  biosimulations/apps/dispatch/.eslintrc
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/browse/example-simulations.json
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/assets/config.json
  biosimulations/apps/dispatch/src/environments/environment.dev.ts
  biosimulations/apps/dispatch/src/environments/environment.prod.ts
  biosimulations/apps/dispatch/src/environments/environment.ts
  biosimulations/apps/platform/.eslintrc
  biosimulations/apps/platform/src/app/models/browse-models/browse-models-datasource.ts
  biosimulations/apps/platform/src/app/models/services/mockModels.ts
  biosimulations/apps/platform/src/app/shared/views/index.ts
  biosimulations/apps/platform/src/environments/environment.prod.ts
  biosimulations/apps/platform/src/environments/environment.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.controller.ts
  biosimulations/apps/simulators-api/src/simulators/simulators.service.ts
  biosimulations/apps/simulators/.eslintrc
  biosimulations/apps/simulators/src/app/help/help/help.component.html
  biosimulations/apps/simulators/src/app/simulators/browse-simulators/browse-simulators.columns.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/app/standards/simulator-interfaces/simulator-interfaces.component.html
  biosimulations/apps/simulators/src/app/standards/simulator-specs/example-specs.json
  biosimulations/apps/simulators/src/app/standards/simulator-specs/simulator-specs.component.html
  biosimulations/apps/simulators/src/environments/environment.prod.ts
  biosimulations/apps/simulators/src/environments/environment.ts
  biosimulations/libs/config/nest/src/lib/biosimulations-hpc-config.ts
  biosimulations/libs/shared/assets/.eslintrc
  biosimulations/libs/shared/environments/src/lib/environment.stage.ts
  biosimulations/libs/shared/styles/.eslintrc
  biosimulations/libs/shared/ui/src/lib/notice/notice.component.ts
  biosimulations/libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  biosimulations/libs/shared/ui/src/lib/toc/toc-section.directive.ts
  biosimulations/libs/shared/ui/src/lib/toc/toc-sections-container.directive.ts
  biosimulations/libs/simulators/api-models/src/lib/biosimulatorsMeta.ts
  biosimulations/libs/simulators/api-models/src/lib/simulator.ts
  biosimulations/libs/simulators/database-models/src/lib/ontologyId.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: reviewed-approved

#1918 Authmethods
  biosimulations/angular.json
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/archiver/archiver.service.ts
  biosimulations/apps/dispatch-service/src/app/services/auth/auth.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/services/auth/auth.service.ts
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/submission/submission.service.ts
  biosimulations/apps/mail-service/src/app/app.controller.ts
  biosimulations/jest.config.js
  biosimulations/libs/auth/client/.eslintrc.json
  biosimulations/libs/auth/client/README.md
  biosimulations/libs/auth/client/jest.config.js
  biosimulations/libs/auth/client/src/index.ts
  biosimulations/libs/auth/client/src/lib/auth-client.module.ts
  biosimulations/libs/auth/client/src/lib/auth-client.service.spec.ts
  biosimulations/libs/auth/client/src/lib/auth-client.service.ts
  biosimulations/libs/auth/client/tsconfig.json
  biosimulations/libs/auth/client/tsconfig.lib.json
  biosimulations/libs/auth/client/tsconfig.spec.json
  biosimulations/libs/dispatch/nest-client/src/lib/auth.service.spec.ts
  biosimulations/libs/dispatch/nest-client/src/lib/auth.service.ts
  biosimulations/libs/dispatch/nest-client/src/lib/dispatch-nest-client.module.ts
  biosimulations/libs/dispatch/nest-client/src/lib/simulation-run.service.spec.ts
  biosimulations/libs/dispatch/nest-client/src/lib/simulation-run.service.ts
  biosimulations/nx.json
  biosimulations/tsconfig.base.json
Labels: PR: unreviewed

#1921 connecting list of available simulation tools in dispatch app to biosimulators database
  biosimulations/apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
Labels: PR: reviewed-approved

#1920 Update Ontologies
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/linguist.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
  biosimulations/libs/ontology/sources/src/lib/sio.json
Labels: PR: reviewed-approved, automerge

#1922 update packages
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1927 Add Permissions to email info
  biosimulations/angular.json
  biosimulations/apps/account-api/src/app/app.controller.spec.ts
  biosimulations/apps/account-api/src/app/app.module.ts
  biosimulations/apps/account-api/src/app/app.service.spec.ts
  biosimulations/apps/account-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/jest.config.js
  biosimulations/libs/account/management/.eslintrc.json
  biosimulations/libs/account/management/README.md
  biosimulations/libs/account/management/jest.config.js
  biosimulations/libs/account/management/src/index.ts
  biosimulations/libs/account/management/src/lib/account-management.module.ts
  biosimulations/libs/account/management/src/lib/management.service.ts
  biosimulations/libs/account/management/tsconfig.json
  biosimulations/libs/account/management/tsconfig.lib.json
  biosimulations/libs/account/management/tsconfig.spec.json
  biosimulations/libs/auth/nest/src/index.ts
  biosimulations/libs/auth/nest/src/lib/authz/authz.service.ts
  biosimulations/libs/auth/nest/src/lib/biosimulations-auth.module.ts
  biosimulations/libs/auth/nest/src/lib/jwt/anoynmous.guard.ts
  biosimulations/libs/auth/nest/src/lib/jwt/optionalAuth.decorator.ts
  biosimulations/libs/auth/nest/src/lib/permissions/permissions.decorator.ts
  biosimulations/libs/auth/nest/src/lib/permissions/permissions.guard.ts
  biosimulations/libs/auth/nest/src/lib/strategy/anonymous.strategy.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRun.ts
  biosimulations/nx.json
  biosimulations/tsconfig.base.json
Labels: PR: unreviewed

#1932 handle invalid id's as 404s
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
Labels: PR: unreviewed

#1946 Remove logging of results
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
Labels: PR: unreviewed

#1947 Optimize Docker Images
  Dockerfile
  biosimulations/package.json
Labels: PR: unreviewed

#1945 add controller for image generation
  biosimulations/apps/dispatch-api/src/app/app.module.ts
  biosimulations/apps/dispatch-api/src/images/image.dto.ts
  biosimulations/apps/dispatch-api/src/images/images.controller.spec.ts
  biosimulations/apps/dispatch-api/src/images/images.controller.ts
  biosimulations/apps/dispatch-api/src/images/images.module.ts
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
  biosimulations/apps/dispatch-service/src/images/images.controller.spec.ts
  biosimulations/apps/dispatch-service/src/images/images.controller.ts
  biosimulations/apps/dispatch-service/src/images/images.module.ts
  biosimulations/apps/dispatch-service/src/images/images.service.spec.ts
  biosimulations/apps/dispatch-service/src/images/images.service.ts
  biosimulations/libs/messages/messages/src/index.ts
  biosimulations/libs/messages/messages/src/lib/images.ts
Labels: PR: reviewed-approved

#1948 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1962 Error reporting
  Dockerfile
  biosimulations/apps/account/tsconfig.app.json
  biosimulations/apps/account/tsconfig.spec.json
  biosimulations/apps/dispatch/tsconfig.app.json
  biosimulations/apps/dispatch/tsconfig.spec.json
  biosimulations/apps/platform/tsconfig.app.json
  biosimulations/apps/platform/tsconfig.spec.json
  biosimulations/apps/simulators/tsconfig.app.json
  biosimulations/apps/simulators/tsconfig.spec.json
  biosimulations/declarations.d.ts
  biosimulations/libs/config/common/src/lib/urls.ts
  biosimulations/libs/platform/view/tsconfig.spec.json
  biosimulations/libs/shared/content/tsconfig.spec.json
  biosimulations/libs/shared/ui/src/lib/error/error-handler.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1966 Error reporting
  biosimulations/libs/shared/ui/.eslintrc
  biosimulations/libs/shared/ui/src/lib/error/error-handler.ts
Labels: PR: unreviewed

#1979 Revert "Bump @sendgrid/mail from 7.4.1 to 7.4.2 in /biosimulations"
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1965 Update Dependency Licenses
  LICENSE-DEPENDENCIES
Labels: PR: reviewed-approved, automerge

#1990 Potential fix for docker npm issues
  .github/workflows/ci.yml
Labels: PR: unreviewed

#1993 validating that algorithms and parameters of simulators have unique KiSAO ids
  biosimulations/libs/simulators/database-models/src/lib/algorithm.ts
  biosimulations/libs/simulators/database-models/src/lib/simulator.ts
Labels: PR: unreviewed

#1986 starting UI component for more granular simulation logs
  biosimulations/apps/dispatch/src/app/components/simulations/simulations.module.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/raw-simulation-log.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/raw-simulation-log.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/raw-simulation-log.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/raw-simulation-log.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.module.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.scss
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/datamodel.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/services/ontology/ontology.service.ts
  biosimulations/apps/dispatch/src/app/simulation-logs-datamodel.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.interface.ts
  biosimulations/apps/simulators/src/app/simulators/view-simulator/view-simulator.service.ts
  biosimulations/apps/simulators/src/app/standards/simulation-logs/final-failed-doc-level-log.json
  biosimulations/apps/simulators/src/app/standards/simulation-logs/final-failed-element-level-log.json
  biosimulations/apps/simulators/src/app/standards/simulation-logs/final-succeeded-element-level-log.json
  biosimulations/apps/simulators/src/app/standards/simulation-logs/init-element-level-log.json
  biosimulations/declarations.d.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRunLog.ts
  biosimulations/libs/shared/icons/src/lib/icon/icon.component.ts
  biosimulations/libs/shared/icons/src/lib/shared-icons.module.ts
  biosimulations/libs/shared/styles/src/lib/_global.scss
  biosimulations/libs/shared/styles/src/lib/biosimulations/biosimulations-colors.scss
  biosimulations/libs/shared/styles/src/lib/biosimulators/biosimulations-colors.scss
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-content-section.component.html
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-content-section.component.scss
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-content-section.component.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-section.component.html
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-section.component.scss
  biosimulations/libs/shared/ui/src/lib/text-page/text-page-section.component.ts
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.html
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.scss
  biosimulations/libs/shared/ui/src/lib/text-page/text-page.component.ts
  biosimulations/package-lock.json
  biosimulations/package.json
Labels: PR: unreviewed

#1992 Update Ontologies
  biosimulations/libs/ontology/sources/src/lib/kisao.json
  biosimulations/libs/ontology/sources/src/lib/linguist.json
  biosimulations/libs/ontology/sources/src/lib/sbo.json
Labels: PR: reviewed-approved, automerge

#2005 Refactor Dispatch App
  biosimulations/apps/dispatch/src/app/app.module.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/raw-simulation-log.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.html
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.model.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.service.spec.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/view.service.ts
  biosimulations/apps/dispatch/src/app/datamodel.ts
  biosimulations/apps/dispatch/src/app/services/simulation/simulation.service.ts
  biosimulations/apps/dispatch/src/app/services/visualization/visualization.service.ts
Labels: PR: unreviewed

#2032 fix if statement
  .github/workflows/ci.yml
Labels: PR: unreviewed

#2020 Logging api
  biosimulations/apps/dispatch-api/src/logs/logs.controller.spec.ts
  biosimulations/apps/dispatch-api/src/logs/logs.controller.ts
  biosimulations/apps/dispatch-api/src/logs/logs.model.ts
  biosimulations/apps/dispatch-api/src/logs/logs.module.ts
  biosimulations/apps/dispatch-api/src/logs/logs.service.spec.ts
  biosimulations/apps/dispatch-api/src/logs/logs.service.ts
  biosimulations/apps/dispatch-api/src/results/results.model.ts
  biosimulations/apps/dispatch-api/src/results/results.module.ts
  biosimulations/libs/datamodel/common/src/lib/utils.ts
Labels: PR: unreviewed

#2030 add support for dark mode
  biosimulations/libs/shared/styles/src/lib/biosimulations/biosimulations-colors.scss
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.html
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.scss
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.ts
Labels: PR: unreviewed

#2035 Implement getting and saving logs. Handle older simulations
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/logs/logs.controller.spec.ts
  biosimulations/apps/dispatch-api/src/logs/logs.controller.ts
  biosimulations/apps/dispatch-api/src/logs/logs.dto.ts
  biosimulations/apps/dispatch-api/src/logs/logs.model.ts
  biosimulations/apps/dispatch-api/src/logs/logs.module.ts
  biosimulations/apps/dispatch-api/src/logs/logs.service.spec.ts
  biosimulations/apps/dispatch-api/src/logs/logs.service.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.controller.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.model.ts
  biosimulations/apps/dispatch-api/src/simulation-run/simulation-run.service.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
  biosimulations/apps/dispatch/proxy.conf.json
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/raw-simulation-log.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.ts
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.ts
  biosimulations/apps/dispatch/src/app/services/dispatch/dispatch.service.ts
  biosimulations/apps/dispatch/src/app/simulation-logs-datamodel.ts
  biosimulations/libs/auth/client/src/lib/auth-client.service.spec.ts
  biosimulations/libs/datamodel/common/src/lib/core/simulationRunLog.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRun.ts
  biosimulations/libs/dispatch/api-models/src/lib/simulationRunLog.ts
  biosimulations/libs/dispatch/nest-client/src/lib/simulation-run.service.ts
  biosimulations/libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.html
  biosimulations/package-lock.json
  biosimulations/package.json
  biosimulations/testDir/log.yml
Labels: PR: unreviewed

#2050 Stderr and Stdout Logging
  biosimulations/.eslintrc.json
  biosimulations/apps/dispatch-service/src/app/app.module.ts
  biosimulations/apps/dispatch-service/src/app/results/file.service.ts
  biosimulations/apps/dispatch-service/src/app/results/log.service.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.spec.ts
  biosimulations/apps/dispatch-service/src/app/results/results.service.ts
  biosimulations/apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: PR: unreviewed

#2058 Process logs even in failure
  biosimulations/apps/dispatch-api/src/logs/logs.controller.ts
  biosimulations/apps/dispatch-service/src/app/results/results.controller.ts
Labels: PR: unreviewed

#2066 Encoding fix
  biosimulations/apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.ts
Labels: PR: unreviewed

#2067 Dispatch service fixes
  biosimulations/apps/dispatch-api/src/app/app.controller.ts
  biosimulations/apps/dispatch-api/src/app/app.service.ts
  biosimulations/apps/dispatch-api/src/logs/logs.service.ts
Labels: PR: unreviewed

#2070 Remove file modifiers
  biosimulations/angular.json
  biosimulations/apps/dispatch-api/src/app/app.service.spec.ts
  biosimulations/libs/dispatch/file-modifiers/.eslintrc
  biosimulations/libs/dispatch/file-modifiers/README.md
  biosimulations/libs/dispatch/file-modifiers/jest.config.js
  biosimulations/libs/dispatch/file-modifiers/src/index.ts
  biosimulations/libs/dispatch/file-modifiers/src/lib/dispatch-file-modifiers.ts
  biosimulations/libs/dispatch/file-modifiers/src/lib/index.ts
  biosimulations/libs/dispatch/file-modifiers/tsconfig.json
  biosimulations/libs/dispatch/file-modifiers/tsconfig.lib.json
  biosimulations/libs/dispatch/file-modifiers/tsconfig.spec.json
  biosimulations/nx.json
  biosimulations/tsconfig.base.json
Labels: PR: unreviewed

#2071 Cleanup
  biosimulations/.gitignore
  biosimulations/apps/.gitkeep
  biosimulations/apps/dispatch-api/src/logs/logs.controller.ts
  biosimulations/apps/dispatch-api/src/logs/logs.dto.ts
  biosimulations/apps/dispatch-api/src/logs/logs.model.ts
  biosimulations/apps/dispatch-api/src/logs/logs.service.ts
  biosimulations/apps/dispatch-api/src/results/results.model.ts
  biosimulations/apps/dispatch-api/src/results/results.service.ts
  biosimulations/testDir/log.yml
Labels: PR: unreviewed
