Repository biosimulations/biosimulations, pull requests merged in 2022-02, with the labels that each got.

#4108 docs: add glossary for common terms
  docs/concepts/conventions/index.md
  docs/concepts/conventions/simulation-experiments.md
  docs/concepts/conventions/simulation-project-metadata.md
  docs/concepts/conventions/simulation-run-logs.md
  docs/concepts/conventions/simulation-run-reports.md
  docs/concepts/conventions/simulation-run-visualizations.md
  docs/concepts/conventions/simulator-capabilities.md
  docs/concepts/conventions/simulator-images.md
  docs/concepts/conventions/simulator-interfaces.md
  docs/index.md
  docs/mkdocs.yml
  docs/snippets/glossary.md
  docs/users/api.md
  docs/users/biosimulations-packages.md
  docs/users/biosimulators-packages.md
  docs/users/creating-projects.md
  docs/users/creating-tools.md
  docs/users/creating-vega-visualizations.md
  docs/users/faqs.md
  docs/users/finding-tools.md
  docs/users/index.md
  docs/users/live-tutorials.md
  docs/users/publishing-projects.md
  docs/users/publishing-tools.md
  docs/users/simulating-projects.md
  docs/users/source-model-repositories.md
  docs/users/validating-projects.md
  docs/users/viewing-projects.md
Labels: PR: reviewed-changes-requested

#4122 fix(deps): update nrwl and angular
  nx.json
  package-lock.json
  package.json
Labels: PR: unreviewed

#4138 docs: update links in Readme
  README.md
Labels: PR: partially-approved

#4139 chore: remove unused packages
  package-lock.json
  package.json
Labels: PR: unreviewed

#4142 fix: use custom version of nestjs/bullmq
  apps/api/src/app/app.module.ts
  apps/api/src/health/bullHealthCheck.ts
  apps/api/src/health/health.module.ts
  apps/api/src/simulation-run/simulation-run.controller.ts
  apps/api/src/simulation-run/simulation-run.module.ts
  apps/dispatch-service/src/app/app.module.ts
  apps/dispatch-service/src/app/submission/complete.processor.ts
  apps/dispatch-service/src/app/submission/dispatch.processor.ts
  apps/dispatch-service/src/app/submission/extract.processor.ts
  apps/dispatch-service/src/app/submission/files.proccessor.ts
  apps/dispatch-service/src/app/submission/log.processor.ts
  apps/dispatch-service/src/app/submission/logPost.processor.ts
  apps/dispatch-service/src/app/submission/manifest.processor.ts
  apps/dispatch-service/src/app/submission/metadata.processor.ts
  apps/dispatch-service/src/app/submission/metadataPost.processor.ts
  apps/dispatch-service/src/app/submission/monitor.processor.ts
  apps/dispatch-service/src/app/submission/output.processor.ts
  apps/dispatch-service/src/app/submission/process.processor.ts
  apps/dispatch-service/src/app/submission/publish.processor.ts
  apps/dispatch-service/src/app/submission/sedML.processor.ts
  apps/dispatch-service/src/app/submission/sedmlPost.processor.ts
  apps/dispatch-service/src/app/submission/thumbnails.proccessor.ts
  apps/dispatch-service/src/app/submission/thumbnailsPost.processor.ts
  package-lock.json
  package.json
Labels: PR: unreviewed

#4177 fix(dispatch-service): correct ordering of processing steps in job, clean up log
  apps/api/src/simulation-run/simulation-run.controller.ts
  apps/dispatch-service/src/app/app.module.ts
  apps/dispatch-service/src/app/app.queues.provider.ts
  apps/dispatch-service/src/app/submission/cleanup.processor.ts
  apps/dispatch-service/src/app/submission/complete.processor.ts
  apps/dispatch-service/src/app/submission/dispatch.processor.ts
  apps/dispatch-service/src/app/submission/monitor.processor.ts
  apps/dispatch-service/src/app/submission/process.processor.ts
  libs/messages/messages/src/lib/queues.ts
Labels: PR: unreviewed

#4178 fix(dispatch-service): bind the /tmp directory to /local on HPC
  apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: PR: reviewed-approved

#4181 fix: fix height for consent screen on mobile
  libs/analytics/angular-analytics/src/lib/consent.service.ts
Labels: PR: reviewed-approved

#4187 style(dispatch): fix simple lint warnings in dispatch
  apps/dispatch/src/app/app.component.ts
  apps/dispatch/src/app/components/home/home.component.ts
  apps/dispatch/src/app/components/run/dispatch/dispatch.component.ts
  apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  apps/dispatch/src/app/components/simulations/browse/delete-simulations-dialog.component.ts
  apps/dispatch/src/app/components/simulations/publish/publish.component.ts
  apps/dispatch/src/app/components/simulations/view/overview/overview.component.ts
  apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.ts
  apps/dispatch/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.component.ts
  apps/dispatch/src/app/components/simulations/view/view.component.ts
  apps/dispatch/src/app/services/simulation/simulation.service.ts
Labels: PR: reviewed-approved

#4213 fix(platform): truncate JSON-LD descriptions
  libs/simulation-runs/service/src/lib/view/view.service.ts
Labels: PR: reviewed-approved

#4235 fix(dispatch,platform): align rendering of styles with SED-ML L1V4
  libs/simulation-runs/service/src/lib/sed-plot-2d-visualization/sed-plot-2d-visualization.service.ts
Labels: PR: unreviewed

#4241 Nx migrate
  package-lock.json
  package.json
Labels: dependencies, PR: unreviewed

#4257 feat(dispatch,platform): disabled 2d plots for 1d data
  libs/datamodel/simulation-runs/src/lib/simulation-run.ts
  libs/simulation-runs/service/src/lib/view/view.service.ts
  libs/simulation-runs/ui/src/lib/render-viz/render-viz.component.spec.ts
  libs/simulation-runs/ui/src/lib/select-viz/select-viz.component.html
Labels: testing, datamodel, PR: unreviewed, ui

#4280 fix(api): handled older simulation specifications that lack styles
  apps/api/src/specifications/specifications.controller.ts
Labels: BioSimulations-API

#4306 fix(platform): fixed simulation type labels in project browse controls
  apps/platform/src/app/projects/browse/browse.component.ts
Labels: BioSimulations, ui

#4324 revert(dispatch-service): reverted to reading manifests out of COMBINE archives
  apps/dispatch-service/src/manifest/manifest.service.ts
Labels: simulation-service

#4330 fix(dispatch,platform): fixed size of images in markdown descriptions of projects
  libs/simulation-runs/ui/src/lib/metadata/metadata.component.scss
Labels: ui

#4331 fix(dispatch-service): restored retrying for image refreshing
  apps/dispatch-service/src/app/services/ssh/ssh.service.ts
  apps/dispatch-service/src/images/images.controller.ts
Labels: simulation-service

#4335 fix(dispatch-service): increased reliability of retrieving logs from S3
  apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: simulation-service

#4338 docs: added ModelDB docs
  docs/mkdocs.yml
Labels: documentation

#4345 build: enable production to be deployed even if dev tests failed (and failures were manually reviewed)
  .github/workflows/deploy.yml
Labels: CI/CD

#4351 perf(combine-api): sped up getting specifications of available simulation tools
  apps/combine-api/Dockerfile
  apps/combine-api/src/handlers/run/get_simulators.py
  apps/combine-api/src/handlers/run/utils.py
Labels: docker
