Repository biosimulations/biosimulations, pull requests merged in 2023-08, with the labels that each got.

#4735 feat: adjustments to simulators dispatch and platform apps across repo
  apps/platform/src/app/app.component.html
  apps/platform/src/app/components/projects/view/view.component.scss
  apps/projex/src/app/components/simulations/view/simulation-log/structured-simulation-log-element.service.ts
  apps/projex/src/app/components/simulations/view/view.service.ts
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/simulators/browse-simulators/browse-simulators.component.html
  apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  apps/simulators/src/app/simulators/view-simulator/view-simulator.component.scss
  apps/simulators/src/assets/config.json
  libs/shared/assets/src/assets/images/biosimulators-logo/logo-white-edited.png
  libs/shared/ui/src/lib/home/home-section.component.scss
  libs/shared/ui/src/lib/hover-open-menu/hover-open-menu.component.html
  libs/shared/ui/src/lib/hover-open-menu/hover-open-menu.component.ts
  libs/shared/ui/src/lib/page/page.component.scss
  libs/shared/ui/src/lib/tab-page/tab-page.component.html
  libs/shared/ui/src/lib/table/table-controls.component.html
  libs/shared/ui/src/lib/table/table-controls.component.scss
  libs/shared/ui/src/lib/table/table-tabular-data.component.scss
  libs/shared/ui/src/lib/table/table.component.ts
  libs/shared/ui/src/lib/text-page/text-page-content-section.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.html
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.scss
Labels: BioSimulations, ui, BioSimulators, BioSimulationsBrowse

#4739 fix: adjustments to repo pointing styles and behavior
  apps/dispatch-service/src/metadata/metadata.service.ts
  apps/dispatch/project.json
  apps/dispatch/src/app/app.component.html
  apps/dispatch/src/app/app.component.spec.ts
  apps/dispatch/src/app/app.module.ts
  apps/dispatch/src/app/components/home/home.component.html
  apps/dispatch/src/app/components/home/home.component.scss
  apps/dispatch/src/app/datamodel.ts
  apps/dispatch/src/polyfills.ts
  apps/dispatch/src/styles.scss
  apps/platform/src/app/app.component.html
  apps/platform/src/app/app.component.spec.ts
  apps/platform/src/app/app.module.ts
  apps/platform/src/app/components/home/featured/featured.component.html
  apps/platform/src/app/components/home/featured/featured.component.scss
  apps/platform/src/app/components/home/featured/featured.component.ts
  apps/platform/src/app/components/home/featured/featured.service.ts
  apps/platform/src/app/components/home/home.component.html
  apps/platform/src/app/components/home/home.component.scss
  apps/platform/src/app/datamodel.ts
  apps/platform/src/styles.scss
  apps/simulators/project.json
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/app.component.spec.ts
  apps/simulators/src/app/app.module.ts
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/home/home.component.scss
  apps/simulators/src/app/simulators/browse-simulators/browse-simulators.component.html
  apps/simulators/src/app/simulators/browse-simulators/browse-simulators.component.scss
  apps/simulators/src/app/simulators/view-simulator/view-simulator.component.html
  apps/simulators/src/app/simulators/view-simulator/view-simulator.component.scss
  apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  apps/simulators/src/assets/config.json
  apps/simulators/src/styles.scss
  libs/shared/assets/src/assets/images/default-resource-images/api.png
  libs/shared/assets/src/assets/images/default-resource-images/browse.jpg
  libs/shared/assets/src/assets/images/default-resource-images/convert.jpg
  libs/shared/assets/src/assets/images/default-resource-images/learn.png
  libs/shared/assets/src/assets/images/default-resource-images/publish.jpg
  libs/shared/assets/src/assets/images/default-resource-images/run.jpg
  libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.html
  libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.scss
  libs/shared/ui/src/lib/home/home-section.component.scss
  libs/shared/ui/src/lib/home/home-subsection.component.html
  libs/shared/ui/src/lib/home/home-subsection.component.ts
  libs/shared/ui/src/lib/home/home-teaser-button.component.scss
  libs/shared/ui/src/lib/home/home-teaser.component.scss
  libs/shared/ui/src/lib/tab-page/tab-page.component.html
  libs/shared/ui/src/lib/tab-page/tab-page.component.scss
  libs/shared/ui/src/lib/tab-page/tab-page.component.ts
  libs/shared/ui/src/lib/table/table-tabular-data.component.html
  libs/shared/ui/src/lib/table/table-tabular-data.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.html
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu.component.scss
  libs/shared/ui/src/lib/topbar/topbar.component.html
  libs/shared/ui/src/lib/topbar/topbar.component.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-metadata/validate-metadata.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-metadata/validate-metadata.component.scss
Labels: testing, BioSimulations, runBiosimulations, ui, simulation-service, build, BioSimulators

#4740 fix: repo qa
  apps/dispatch/src/app/app.component.html
  apps/dispatch/src/app/app.component.ts
  apps/dispatch/src/app/components/home/home.component.html
  apps/dispatch/src/app/components/home/home.component.scss
  apps/dispatch/src/app/components/home/home.component.ts
  apps/platform/src/app/app.component.html
  apps/platform/src/app/app.component.ts
  apps/platform/src/app/components/home/featured/featured.component.html
  apps/platform/src/app/components/home/featured/featured.component.scss
  apps/platform/src/app/components/home/home.component.html
  apps/platform/src/app/components/home/home.component.scss
  apps/platform/src/app/components/home/home.component.ts
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/app.component.ts
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/home/home.component.scss
  apps/simulators/src/app/home/home.component.spec.ts
  apps/simulators/src/app/home/home.component.ts
  libs/config/common/src/lib/endpoints.ts
  libs/shared/styles/src/lib/_global.scss
  libs/shared/styles/src/lib/biosimulations-theme.scss
  libs/shared/ui/src/lib/home/home-section.component.scss
  libs/shared/ui/src/lib/logo-image/logo-image.component.ts
Labels: testing, BioSimulations, runBiosimulations, ui, BioSimulators

#4741 style(ui): adjustments to simulators home and global styles
  apps/dispatch/src/app/app.component.html
  apps/dispatch/src/app/components/home/home.component.html
  apps/dispatch/src/app/components/home/home.component.scss
  apps/dispatch/src/app/components/run/dispatch/dispatch.component.scss
  apps/platform/src/app/app.component.html
  apps/platform/src/app/app.component.ts
  apps/platform/src/app/components/home/home.component.html
  apps/platform/src/app/components/home/home.component.scss
  apps/platform/src/app/components/home/home.component.ts
  apps/platform/src/app/components/run/dispatch/dispatch.component.html
  apps/platform/src/app/components/run/dispatch/dispatch.component.scss
  apps/projex/src/app/app.component.html
  apps/projex/src/app/app.component.scss
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/home/home.component.scss
  libs/analytics/angular-analytics/src/lib/cookie-consent/cookie-consent.component.html
  libs/analytics/angular-analytics/src/lib/cookie-consent/cookie-consent.component.scss
  libs/shared/environments/src/lib/environment.ts
  libs/shared/styles/src/lib/_global.scss
  libs/shared/ui/src/lib/hover-open-menu/hover-open-menu.component.ts
Labels: BioSimulations, runBiosimulations, ui, BioSimulators, BioSimulationsBrowse

#4742 feat: cross repo app routing implementation
  apps/dispatch/src/app/app.component.html
  apps/dispatch/src/app/app.component.ts
  apps/dispatch/src/app/components/home/home.component.html
  apps/dispatch/src/app/components/home/home.component.ts
  apps/dispatch/src/app/components/simulations/browse/browse.component.ts
  apps/dispatch/src/assets/config.json
  apps/platform/src/app/app.component.html
  apps/platform/src/app/app.component.ts
  apps/platform/src/app/components/home/home.component.html
  apps/platform/src/app/components/home/home.component.ts
  apps/platform/src/app/components/simulations/browse/browse.component.ts
  apps/platform/src/app/components/simulations/view/view.service.ts
  apps/platform/src/assets/config.json
  apps/projex/src/app/app.component.html
  apps/projex/src/app/app.component.ts
  apps/projex/src/app/components/home/home.component.html
  apps/projex/src/app/components/home/home.component.ts
  apps/projex/src/app/components/simulations/browse/browse.component.ts
  apps/projex/src/assets/config.json
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/app.component.ts
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/home/home.component.ts
  apps/simulators/src/app/simulators/view-simulator/view-simulator.component.ts
  apps/simulators/src/assets/config.json
  libs/config/angular/src/lib/config/config.service.ts
  libs/config/common/src/lib/app-routes.ts
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.html
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.scss
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.spec.ts
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.ts
  libs/shared/ui/src/lib/shared-ui.module.ts
Labels: testing, BioSimulations, runBiosimulations, ui, BioSimulators, BioSimulationsBrowse

#4743 fix: removed unused code in notice css file
  libs/shared/ui/src/lib/notice/notice.component.scss
Labels: ui

#4744 fix: removed comments and unused code to appease CI/CD
  apps/dispatch/project.json
  apps/dispatch/src/app/components/simulations/view/overview/overview.component.scss
  apps/dispatch/src/app/components/simulations/view/overview/overview.component.ts
  apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.scss
  apps/dispatch/src/styles.scss
  apps/platform/project.json
  apps/platform/src/app/components/projects/view/view.component.scss
  apps/platform/src/styles.scss
  apps/projex/project.json
  apps/projex/src/app/app.component.ts
  apps/projex/src/app/components/home/featured/featured.component.scss
  apps/projex/src/app/components/projects/project-table/project-table.component.scss
  apps/projex/src/app/components/projects/view/view.component.scss
  apps/projex/src/app/components/run/dispatch/dispatch.component.scss
  apps/projex/src/app/components/simulations/view/overview/overview.component.scss
  apps/projex/src/app/components/simulations/view/overview/overview.component.ts
  apps/projex/src/app/components/simulations/view/simulation-log/simulation-log.component.scss
  apps/projex/src/styles.scss
  apps/simulators/project.json
  apps/simulators/src/styles.scss
  libs/shared/styles/src/lib/biosimulations-typography.scss
  libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.scss
  libs/shared/ui/src/lib/bread-crumbs/bread-crumbs.component.scss
  libs/shared/ui/src/lib/carousel/carousel.component.scss
  libs/shared/ui/src/lib/dropdown-menu-item/dropdown-menu-item.component.scss
  libs/shared/ui/src/lib/home/home-section.component.scss
  libs/shared/ui/src/lib/home/home-subsection.component.scss
  libs/shared/ui/src/lib/home/home-teaser-button.component.scss
  libs/shared/ui/src/lib/home/home-teaser.component.scss
  libs/shared/ui/src/lib/home/home-teaser.component.ts
  libs/shared/ui/src/lib/html-snack-bar/html-snack-bar.component.scss
  libs/shared/ui/src/lib/logo-text/logo-text.component.scss
  libs/shared/ui/src/lib/page/page.component.scss
  libs/shared/ui/src/lib/text-page/text-page-section.component.scss
  libs/shared/ui/src/lib/text-page/text-page-side-bar-section.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu.component.scss
  libs/shared/ui/src/lib/topbar/topbar.component.scss
  libs/simulation-runs/ui/src/lib/files/files.component.scss
  libs/simulation-runs/ui/src/lib/files/files.component.ts
  libs/simulation-runs/ui/src/lib/metadata/metadata.component.scss
Labels: BioSimulations, runBiosimulations, ui, build, BioSimulators, BioSimulationsBrowse

#4747 fix: cross-repo content adjustments
  apps/dispatch/src/app/app.component.html
  apps/dispatch/src/app/components/home/home.component.html
  apps/dispatch/src/app/components/home/home.component.scss
  apps/dispatch/src/app/components/home/home.component.ts
  apps/dispatch/src/app/components/simulations/browse/browse.component.html
  apps/dispatch/src/app/components/simulations/browse/browse.component.scss
  apps/dispatch/src/app/components/simulations/browse/delete-simulations-dialog.component.html
  apps/dispatch/src/styles.scss
  apps/platform/src/app/app.component.html
  apps/platform/src/app/app.component.ts
  apps/platform/src/app/components/home/home.component.html
  apps/platform/src/app/components/projects/project-table/project-table.component.html
  apps/platform/src/app/components/projects/project-table/project-table.component.scss
  apps/platform/src/app/components/simulations/browse/browse.component.html
  apps/platform/src/app/components/simulations/browse/delete-simulations-dialog.component.html
  apps/platform/src/assets/config.json
  apps/platform/src/styles.scss
  apps/projex/src/app/app.component.html
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/app.component.ts
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/home/home.component.scss
  apps/simulators/src/app/simulators/browse-simulators/browse-simulators.component.html
  apps/simulators/src/app/simulators/browse-simulators/browse-simulators.component.scss
  apps/simulators/src/styles.scss
  libs/config/angular/src/lib/config/config.service.ts
  libs/shared/styles/src/lib/_global.scss
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.html
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.scss
  libs/shared/ui/src/lib/home/home-teaser-button.component.scss
  libs/shared/ui/src/lib/home/home-teaser.component.html
  libs/shared/ui/src/lib/page/page.component.html
  libs/shared/ui/src/lib/page/page.component.scss
  libs/shared/ui/src/lib/shared-ui.module.ts
  libs/shared/ui/src/lib/table/responsive-table.component.scss
Labels: BioSimulations, runBiosimulations, ui, BioSimulators, BioSimulationsBrowse

#4748 fix: adjusted hero banner color for simulators app to align with logo color
  apps/platform/src/app/components/home/featured/featured.component.scss
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/app/home/home.component.scss
  apps/simulators/src/assets/config.json
  libs/shared/styles/src/lib/_global.scss
  libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.html
  libs/shared/ui/src/lib/biosimulations-navigation/biosimulations-navigation.component.ts
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.html
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.ts
  libs/shared/ui/src/lib/table/table-tabular-data.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.html
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.ts
Labels: BioSimulations, ui, BioSimulators

#4749 fix: adjustment to platform specific home page styling
  apps/dispatch/src/app/components/home/home.component.html
  apps/platform/src/app/components/home/featured/featured.component.scss
  apps/platform/src/app/components/home/featured/featured.service.ts
  apps/platform/src/app/components/home/home.component.html
  apps/simulators/src/app/home/home.component.scss
  libs/shared/styles/src/lib/_global.scss
Labels: BioSimulations, runBiosimulations, ui, BioSimulators

#4752 fix: cross-repo style and behavior adjustment
  apps/dispatch/src/app/app.component.html
  apps/dispatch/src/app/components/home/home.component.html
  apps/dispatch/src/app/components/home/home.component.scss
  apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.html
  apps/dispatch/src/app/components/simulations/view/simulation-log/simulation-log.component.scss
  apps/platform/src/app/components/home/home.component.scss
  apps/platform/src/app/components/run/dispatch/dispatch.component.html
  apps/platform/src/app/components/run/dispatch/dispatch.component.scss
  apps/simulators/src/app/app.component.html
  apps/simulators/src/app/app.component.ts
  apps/simulators/src/app/home/home.component.html
  apps/simulators/src/styles.scss
  libs/shared/styles/src/lib/_global.scss
  libs/shared/ui/src/lib/hero-banner-util-button/hero-banner-util-button.component.ts
  libs/shared/ui/src/lib/home/home-section.component.html
  libs/shared/ui/src/lib/home/home-subsection.component.html
  libs/shared/ui/src/lib/home/home-subsection.component.scss
  libs/shared/ui/src/lib/home/home-subsection.component.ts
  libs/shared/ui/src/lib/hover-open-menu/hover-open-menu.component.html
  libs/shared/ui/src/lib/hover-open-menu/hover-open-menu.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.html
  libs/shared/ui/src/lib/topbar/topbar-menu-item.component.scss
  libs/shared/ui/src/lib/topbar/topbar-menu.component.html
  libs/shared/ui/src/lib/topbar/topbar-menu.component.scss
  libs/shared/ui/src/lib/topbar/topbar.component.html
  libs/shared/ui/src/lib/topbar/topbar.component.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/create-project/create-project/create-project.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/create-project/create-project/forms/paging-form/paging-form.component.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-simulation/validate-simulation.component.html
Labels: BioSimulations, runBiosimulations, ui, BioSimulators

#4754 style(ui): adjusted dispatch run header and submit button styles
  apps/dispatch/src/app/app.module.ts
  apps/dispatch/src/app/components/run/dispatch/dispatch.component.html
  apps/dispatch/src/app/components/run/dispatch/dispatch.component.scss
  apps/dispatch/src/app/components/simulations/simulations.module.ts
  apps/dispatch/src/app/components/simulations/view/overview/overview.component.html
  apps/dispatch/src/app/components/simulations/view/overview/overview.component.scss
  apps/dispatch/src/app/components/simulations/view/overview/overview.component.spec.ts
  apps/dispatch/src/app/components/simulations/view/view.component.html
  apps/dispatch/src/app/components/simulations/view/view.component.scss
  apps/simulators/src/app/app.component.html
  libs/shared/styles/src/lib/_global.scss
  libs/shared/ui/src/lib/page/page.component.scss
  libs/shared/ui/src/lib/tab-page/tab-page.component.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/convert-file/convert-file.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/create-project/create-project/forms/paging-form/paging-form.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/create-project/create-project/forms/paging-form/paging-form.component.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/create-project/form-steps/form-steps.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/suggest-simulator/suggest-simulator.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-metadata/validate-metadata.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-metadata/validate-metadata.component.scss
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-model/validate-model.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-project/validate-project.component.html
  libs/simulation-project-utils/simulation-project-utils/src/lib/ui/validate-simulation/validate-simulation.component.html
  libs/simulation-runs/ui/src/lib/metadata/metadata.component.html
  libs/simulation-runs/ui/src/lib/metadata/metadata.component.scss
Labels: testing, runBiosimulations, ui, BioSimulators

#4755 fix: disable COBRApy and RBApy deploy tests until new Gurobi license
  tools/example-projects.json
Labels: CI/CD, deployment

#4756 fix: force build test deploy workflow for merged PR 4755
  .github/workflows/deploy.yml
  apps/platform/src/app/app.component.html
Labels: BioSimulations, CI/CD, ui, deployment

#4758 fix: update hsload args for h5pyd 0.14.1 to upload to HSDS from Slurm
  apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: bug, simulation-service

#4759 fix: removed other switch
  apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: bug, simulation-service

#4760 fix: HSDS upload HPC Jobs to retry randomly many times upon failure
  apps/dispatch-service/src/app/services/sbatch/sbatch.service.ts
Labels: bug, simulation-service

#4757 fix: repo touch-ups
  apps/platform/src/app/components/projects/project-table/project-table.component.scss
  apps/platform/src/app/components/projects/view/view.component.html
  apps/platform/src/app/components/projects/view/view.component.scss
  libs/shared/styles/src/lib/_global.scss
  libs/shared/ui/src/lib/app-footer/app-footer.component.html
  libs/shared/ui/src/lib/app-footer/app-footer.component.scss
  libs/shared/ui/src/lib/app-footer/app-footer.component.ts
  libs/shared/ui/src/lib/carousel/carousel.component.html
  libs/shared/ui/src/lib/carousel/carousel.component.scss
  libs/shared/ui/src/lib/home/home-subsection.component.scss
  libs/simulation-runs/ui/src/lib/files/files.component.html
  libs/simulation-runs/ui/src/lib/files/files.component.scss
  libs/simulation-runs/ui/src/lib/metadata/metadata.component.html
Labels: BioSimulations, ui
